version: '3'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile-dev
    ports:
      - "4200:4200"
      - "49153:49153"
    command: npm start -- --host 0.0.0.0
    environment:
      NODE_ENV: development
    volumes:
          - ./web:/usr/app/
          - /usr/app/node_modules
    links:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    command: npm start
    ports:
      - "3000:3000"
